### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Karyum** [FACN4/week4_espionageProject#33]
The README is lovely but there are couple of stuff missing from it, for example local instructions how to clone install and run the app, right now this doesn't look very important but in the future when the projects get bigger it's **really** important. also the user stories are no where near user stories you dont even mention the picture you would get after you search

_personally not a fan of READMEs done by developers but we have to do them....._

**Comment by Ryan2601** [comment]
Agree that the README is very nice.

**Comment by Karyum** [comment]
also maybe add a project description
