### ISSUE TITLE
API KEY on github

### ISSUE THREAD

**Issue by Karyum** [FACN4/week4_espionageProject#37]
not a big deal right now, but just im raising this issue just cause anyone could take your key and use it https://github.com/FACN4/week4_espionageProject/blob/master/public/xhr.js#L20
but i guess it's fine for now since env vars haven't been taught yet

**Comment by Karyum** [comment]
also i love the comments on your code

**Comment by DenisKent** [comment]
Thanks Mario. Yeah if we had more time we would have put the api codes on the server side.
