### ISSUE TITLE
the main idea is gallery of cities while..

### ISSUE THREAD

**Issue by Solk10** [FACN4/week4_espionageProject#41]
you have other pictures showing up that has nothing to do with the main idea ..
![screenshot from 2018-07-26 10-41-24](https://user-images.githubusercontent.com/39616416/43248528-d122f8d2-90c0-11e8-85fe-e422c039ab71.png)

**Comment by tawfiknasser** [comment]
city of diamonds :gem: 
this related to the API we used,
we will try to use better API
