### ISSUE TITLE
weird names of cities showing up , not sure they exist at all

### ISSUE THREAD

**Issue by Solk10** [FACN4/week4_espionageProject#42]
🤔
![screenshot from 2018-07-26 10-47-30](https://user-images.githubusercontent.com/39616416/43248815-a9f6b8b0-90c1-11e8-9548-f7843f54e04a.png)

**Comment by Solk10** [comment]
🤔
![screenshot from 2018-07-26 10-47-30](https://user-images.githubusercontent.com/39616416/43248715-6a781792-90c1-11e8-9756-f17df143ae13.png)

**Comment by DenisKent** [comment]
Did you check?
![image](https://user-images.githubusercontent.com/28222381/43249238-df0b837c-90c2-11e8-8e19-baeeeb82e3e6.png)

**Comment by Solk10** [comment]
yeah this one i have afterwards.. but others still in doubt
